source 'https://rubygems.org'

# dev for emacs
gem "pry"
gem "pry-byebug"
gem "pry-doc"
gem "pry-rails"

# tools
gem "org-ruby"
gem "rouge"
gem "nokogiri"

# gitlab
gem "gitlab" # see "https://github.com/NARKOZ/gitlab"
