# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  background-image = {
    pname = "background-image";
    version = "2025-11-15";
    src = fetchurl {
      url = "https://wiki.haskell.org/wikistatic/haskellwiki_logo.png";
      sha256 = "sha256-NVUPqd/3lxzRPrTfBCBXgxrXR3blEJC/XiJ1nAEcaPQ=";
    };
  };
  easypulse = {
    pname = "easypulse";
    version = "cf78ac20c76bc3e5b82ce3d21475a32c8a1f76d3";
    src = fetchFromGitHub {
      owner = "p-chan5";
      repo = "EasyPulse";
      rev = "cf78ac20c76bc3e5b82ce3d21475a32c8a1f76d3";
      fetchSubmodules = false;
      sha256 = "sha256-xielIfPNTdSx/mHRuoOLHQKaeo3jOTdBitin6A/QBh4=";
    };
    date = "2025-08-27";
  };
  fcitx5-dracula = {
    pname = "fcitx5-dracula";
    version = "a267e6f6aea361f3ebf2f8cd3b1e56c134321a2d";
    src = fetchFromGitHub {
      owner = "drbbr";
      repo = "fcitx5-dracula-theme";
      rev = "a267e6f6aea361f3ebf2f8cd3b1e56c134321a2d";
      fetchSubmodules = false;
      sha256 = "sha256-aah25igObbTXjQZEFIsfmj94S4PeZ0ay3P/OBtE6WnE=";
    };
    date = "2023-07-02";
  };
  fortune-chinese = {
    pname = "fortune-chinese";
    version = "000fb01261e4d119e4e988ce82f49fb8b139fe3c";
    src = fetchFromGitHub {
      owner = "ruanyf";
      repo = "fortunes";
      rev = "000fb01261e4d119e4e988ce82f49fb8b139fe3c";
      fetchSubmodules = false;
      sha256 = "sha256-O258vnAHQ3RrJnMPmVntmkj+RSfpHsf/YKJcLZd0owc=";
    };
    date = "2021-08-13";
  };
  jackhack96Easyeffects = {
    pname = "jackhack96Easyeffects";
    version = "069195c4e73d5ce94a87acb45903d18e05bffdcc";
    src = fetchFromGitHub {
      owner = "JackHack96";
      repo = "EasyEffects-Presets";
      rev = "069195c4e73d5ce94a87acb45903d18e05bffdcc";
      fetchSubmodules = false;
      sha256 = "sha256-nXVtX0ju+Ckauo0o30Y+sfNZ/wrx3HXNCK05z7dLaFc=";
    };
    date = "2025-01-02";
  };
  rime-cangjie = {
    pname = "rime-cangjie";
    version = "0ac8452eeb4abbcd8dd1f9e7314012310743285f";
    src = fetchFromGitHub {
      owner = "rime";
      repo = "rime-cangjie";
      rev = "0ac8452eeb4abbcd8dd1f9e7314012310743285f";
      fetchSubmodules = false;
      sha256 = "sha256-v8n3+73l9YbTexpA9C2356quioRwFRVcBY0IncolVoY=";
    };
    date = "2024-03-25";
  };
  rime-japanese = {
    pname = "rime-japanese";
    version = "4c1e65135459175136f380e90ba52acb40fdfb2d";
    src = fetchFromGitHub {
      owner = "gkovacs";
      repo = "rime-japanese";
      rev = "4c1e65135459175136f380e90ba52acb40fdfb2d";
      fetchSubmodules = false;
      sha256 = "sha256-/mIIyCu8V95ArKo/vIS3qAiD8InUmk8fAF/wejxRxGw=";
    };
    date = "2023-08-02";
  };
  rime-prelude = {
    pname = "rime-prelude";
    version = "3c602fdb0dcca7825103e281efc50ef7580f99ec";
    src = fetchFromGitHub {
      owner = "rime";
      repo = "rime-prelude";
      rev = "3c602fdb0dcca7825103e281efc50ef7580f99ec";
      fetchSubmodules = false;
      sha256 = "sha256-R9sxeCe1e2A3pn//iGwRr3eTTpgxprjEEjlo15/O19c=";
    };
    date = "2025-04-20";
  };
  rime-wubi86-jidian = {
    pname = "rime-wubi86-jidian";
    version = "f30dc398c1db6faf7bb198333fb1145df3c3085b";
    src = fetchFromGitHub {
      owner = "KyleBing";
      repo = "rime-wubi86-jidian";
      rev = "f30dc398c1db6faf7bb198333fb1145df3c3085b";
      fetchSubmodules = false;
      sha256 = "sha256-RkAry44d8YB22jAH4pXdJOEgOiLEeCII97vRFmHWa0Y=";
    };
    date = "2025-06-08";
  };
  vonfry-icon = {
    pname = "vonfry-icon";
    version = "2025-11-15";
    src = fetchurl {
      url = "https://vonfry.name/images/default/logo-white.png";
      sha256 = "sha256-57Vf7OS5H6va5M5Tmx87FmpSZtIlqldeiBkwcbrrEm0=";
    };
  };
}
