system-ghc: false
templates:
  params:
    author-name: Vonfry
    author-email: vonfry314@gmail.com
    copyright: 'Copyright: ©  2018 Vonfry'
    github-username: VonFry
    scm-init: git
save-hackage-creds: true

package-indices:
  - name: Tsinghua
    download-prefix: https://mirrors.tuna.tsinghua.edu.cn/hackage/package/
    http: https://mirrors.tuna.tsinghua.edu.cn/hackage/01-index.tar.gz

setup-info: "https://mirrors.tuna.tsinghua.edu.cn/stackage/stack-setup.yaml"
urls:
  latest-snapshot: https://mirrors.tuna.tsinghua.edu.cn/stackage/snapshots.json
  lts-build-plans: https://mirrors.tuna.tsinghua.edu.cn/stackage/lts-haskell/
  nightly-build-plans: https://mirrors.tuna.tsinghua.edu.cn/stackage/stackage-nightly/
