"" nmap.vim
" normal map keybind, this will depead to leader.

let g:vonfry#keybind#nmap#leader = "\<Space>"

let g:vonfry#keybind#nmap#x = "x"
let g:vonfry#keybind#nmap#go = '.'
let g:vonfry#keybind#nmap#go_back = ','
let g:vonfry#keybind#nmap#go_peek = '{'
let g:vonfry#keybind#nmap#go_reference = '}'
let g:vonfry#keybind#nmap#code = ';'
let g:vonfry#keybind#nmap#swiper = '/'
let g:vonfry#keybind#nmap#go_prompt = '>'
let g:vonfry#keybind#nmap#code_help = '?'
let g:vonfry#keybind#nmap#go_module = '#'
let g:vonfry#keybind#nmap#format = '('
let g:vonfry#keybind#nmap#align = '='
let g:vonfry#keybind#nmap#speedbar = '&'
let g:vonfry#keybind#nmap#repl = '''
let g:vonfry#keybind#nmap#lang_action = '*'
let g:vonfry#keybind#nmap#navigation = '['
let g:vonfry#keybind#nmap#g = 'g'
let g:vonfry#keybind#nmap#buffer_switch = 'b'
let g:vonfry#keybind#nmap#buffer = 'B'
let g:vonfry#keybind#nmap#marks = 'm'
let g:vonfry#keybind#nmap#book_marks = 'K'
let g:vonfry#keybind#nmap#run = 'r'
let g:vonfry#keybind#nmap#search = 'a'
let g:vonfry#keybind#nmap#ctrlp = 'p'
let g:vonfry#keybind#nmap#file = 'f'
let g:vonfry#keybind#nmap#tag = 't'
let g:vonfry#keybind#nmap#treenode = 'd'
let g:vonfry#keybind#nmap#check = 'q'
let g:vonfry#keybind#nmap#undotree = 'u'
let g:vonfry#keybind#nmap#window = 'w'
let g:vonfry#keybind#nmap#commenter = 'c'
let g:vonfry#keybind#nmap#virtual = 'v'
let g:vonfry#keybind#nmap#terminal = '$'
let g:vonfry#keybind#nmap#version_control = '-'
let g:vonfry#keybind#nmap#highlight = 'h'
let g:vonfry#keybind#nmap#todo = '~'
let g:vonfry#keybind#nmap#lang = 'z'
